///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ServerTimeModel {
/*
{
  "data": "2021-12-21T06:50:47.055320Z",
  "message": "",
  "message_ex": "",
  "success": true,
  "errors": null
} 
*/

  String? data;
  String? message;
  String? messageEx;
  bool? success;
  String? errors;

  ServerTimeModel({
    this.data,
    this.message,
    this.messageEx,
    this.success,
    this.errors,
  });
  ServerTimeModel.fromJson(Map<String, dynamic> json) {
    data = json['data']?.toString();
    message = json['message']?.toString();
    messageEx = json['message_ex']?.toString();
    success = json['success'];
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data;
    data['message'] = message;
    data['message_ex'] = messageEx;
    data['success'] = success;
    data['errors'] = errors;
    return data;
  }
}
