///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserTimeStampModelDataEmpInfo {


  String? id;
  String? username;
  String? password;
  String? userLevel;
  String? userType;
  String? companyId;
  String? sysCustomerCode;
  String? profileImg;
  String? isActive;
  String? isDelete;
  String? remark;
  String? empImg;
  String? titleName;
  String? name;
  String? titleNameEn;
  String? nameEn;
  String? citizenId;
  String? taxId;
  String? socialInsuranceId;
  String? nickName;
  String? gender;
  String? weight;
  String? height;
  String? birthdate;
  String? bloodGroup;
  String? nationalityId;
  String? religionId;
  String? militaryStatus;
  String? marriedStatus;
  String? tel;
  String? socialContact_1;
  String? empCode;
  String? empTypeId;
  String? empGroupId;
  String? departmentId;
  String? sectionId;
  String? positionId;
  String? groupDayOfWorkId;
  String? shiftId;
  String? holidayLeave;
  String? fingerSign;
  String? empWorkStatus;
  String? payType;
  String? payTerm;
  String? taxCalcId;
  String? masterBankId;
  String? bankAccountNo;
  String? bankAccountName;
  String? socialInsuranceMethodLv;
  String? contractNo;
  String? hireDate;
  String? hireEnd;
  String? startDate;
  String? dateOfAttendance;
  String? wageValue;
  String? probationDays;
  String? address_1;
  String? provinceId_1;
  String? amphureId_1;
  String? tambolId_1;
  String? postalCode_1;
  String? isSameAddress;
  String? address_2;
  String? provinceId_2;
  String? amphureId_2;
  String? tambolId_2;
  String? postalCode_2;
  String? personRelateName;
  String? personRelateTel;
  String? personRelateDescription;
  String? languageSkill_1;
  String? languagePoint_1;
  String? languageTalk_1;
  String? languageRead_1;
  String? languageWrite_1;
  String? languageSkill_2;
  String? languagePoint_2;
  String? languageTalk_2;
  String? languageRead_2;
  String? languageWrite_2;
  String? motorcycleDrivingSkill;
  String? motorcycleDrivingLicence;
  String? motorcycleHave;
  String? carDrivingSkill;
  String? carDrivingLicence;
  String? carHave;
  String? passportId;
  String? passportDate;
  String? passportEndDate;
  String? visaId;
  String? visaDate;
  String? visaEndDate;
  String? isExpat;
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;
  String? status;
  String? helper;
  String? checkTerms;
  String? sysUserType;
  String? isPermitLogin;
  String? empLevel;
  String? empEducationId;
  String? taxCalcValue;
  String? terminationReportDate;
  String? terminationDate;
  String? terminationApproveBy;
  String? terminationAt;
  String? terminationRemark;
  String? isTermination;
  String? retireDate;
  String? retireReportDate;
  String? retireBy;
  String? retireAt;
  String? retireRemark;
  String? suspendAt;
  String? suspendDate;
  String? suspendReportDate;
  String? suspendBy;
  String? suspendRemark;
  String? quitDate;
  String? quitReportDate;
  String? quitBy;
  String? quitRemark;
  String? quitAt;
  String? ipAddress;
  String? hospitalName;
  String? docName_1;
  String? docNumb_1;
  String? docDate_1;
  String? docEndDate_1;
  String? docAlert_1;
  String? docName_2;
  String? docNumb_2;
  String? docDate_2;
  String? docEndDate_2;
  String? docAlert_2;
  String? docName_3;
  String? docNumb_3;
  String? docDate_3;
  String? docEndDate_3;
  String? docAlert_3;
  String? docName_4;
  String? docNumb_4;
  String? docDate_4;
  String? docEndDate_4;
  String? docAlert_4;
  String? requestDelete;
  String? tourStatus_01;
  String? methodCreateType;
  String? shortcutSetting;
  String? joinDepartment;
  String? joinSection;
  String? joinPosition;
  String? joinBank;
  String? joinGroupDayOfWork;
  String? joinShift;
  String? joinNationality;
  String? joinProvinceId_1;
  String? joinAmphureId_1;
  String? joinTambolId_1;
  String? joinProvinceId_2;
  String? joinAmphureId_2;
  String? joinTambolId_2;
  String? joinEducation;

  UserTimeStampModelDataEmpInfo({
    this.id,
    this.username,
    this.password,
    this.userLevel,
    this.userType,
    this.companyId,
    this.sysCustomerCode,
    this.profileImg,
    this.isActive,
    this.isDelete,
    this.remark,
    this.empImg,
    this.titleName,
    this.name,
    this.titleNameEn,
    this.nameEn,
    this.citizenId,
    this.taxId,
    this.socialInsuranceId,
    this.nickName,
    this.gender,
    this.weight,
    this.height,
    this.birthdate,
    this.bloodGroup,
    this.nationalityId,
    this.religionId,
    this.militaryStatus,
    this.marriedStatus,
    this.tel,
    this.socialContact_1,
    this.empCode,
    this.empTypeId,
    this.empGroupId,
    this.departmentId,
    this.sectionId,
    this.positionId,
    this.groupDayOfWorkId,
    this.shiftId,
    this.holidayLeave,
    this.fingerSign,
    this.empWorkStatus,
    this.payType,
    this.payTerm,
    this.taxCalcId,
    this.masterBankId,
    this.bankAccountNo,
    this.bankAccountName,
    this.socialInsuranceMethodLv,
    this.contractNo,
    this.hireDate,
    this.hireEnd,
    this.startDate,
    this.dateOfAttendance,
    this.wageValue,
    this.probationDays,
    this.address_1,
    this.provinceId_1,
    this.amphureId_1,
    this.tambolId_1,
    this.postalCode_1,
    this.isSameAddress,
    this.address_2,
    this.provinceId_2,
    this.amphureId_2,
    this.tambolId_2,
    this.postalCode_2,
    this.personRelateName,
    this.personRelateTel,
    this.personRelateDescription,
    this.languageSkill_1,
    this.languagePoint_1,
    this.languageTalk_1,
    this.languageRead_1,
    this.languageWrite_1,
    this.languageSkill_2,
    this.languagePoint_2,
    this.languageTalk_2,
    this.languageRead_2,
    this.languageWrite_2,
    this.motorcycleDrivingSkill,
    this.motorcycleDrivingLicence,
    this.motorcycleHave,
    this.carDrivingSkill,
    this.carDrivingLicence,
    this.carHave,
    this.passportId,
    this.passportDate,
    this.passportEndDate,
    this.visaId,
    this.visaDate,
    this.visaEndDate,
    this.isExpat,
    this.createdAt,
    this.createdBy,
    this.updatedAt,
    this.updatedBy,
    this.status,
    this.helper,
    this.checkTerms,
    this.sysUserType,
    this.isPermitLogin,
    this.empLevel,
    this.empEducationId,
    this.taxCalcValue,
    this.terminationReportDate,
    this.terminationDate,
    this.terminationApproveBy,
    this.terminationAt,
    this.terminationRemark,
    this.isTermination,
    this.retireDate,
    this.retireReportDate,
    this.retireBy,
    this.retireAt,
    this.retireRemark,
    this.suspendAt,
    this.suspendDate,
    this.suspendReportDate,
    this.suspendBy,
    this.suspendRemark,
    this.quitDate,
    this.quitReportDate,
    this.quitBy,
    this.quitRemark,
    this.quitAt,
    this.ipAddress,
    this.hospitalName,
    this.docName_1,
    this.docNumb_1,
    this.docDate_1,
    this.docEndDate_1,
    this.docAlert_1,
    this.docName_2,
    this.docNumb_2,
    this.docDate_2,
    this.docEndDate_2,
    this.docAlert_2,
    this.docName_3,
    this.docNumb_3,
    this.docDate_3,
    this.docEndDate_3,
    this.docAlert_3,
    this.docName_4,
    this.docNumb_4,
    this.docDate_4,
    this.docEndDate_4,
    this.docAlert_4,
    this.requestDelete,
    this.tourStatus_01,
    this.methodCreateType,
    this.shortcutSetting,
    this.joinDepartment,
    this.joinSection,
    this.joinPosition,
    this.joinBank,
    this.joinGroupDayOfWork,
    this.joinShift,
    this.joinNationality,
    this.joinProvinceId_1,
    this.joinAmphureId_1,
    this.joinTambolId_1,
    this.joinProvinceId_2,
    this.joinAmphureId_2,
    this.joinTambolId_2,
    this.joinEducation,
  });
  UserTimeStampModelDataEmpInfo.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    password = json['password']?.toString();
    userLevel = json['user_level']?.toString();
    userType = json['user_type']?.toString();
    companyId = json['company_id']?.toString();
    sysCustomerCode = json['sys_customer_code']?.toString();
    profileImg = json['profile_img']?.toString();
    isActive = json['is_active']?.toString();
    isDelete = json['is_delete']?.toString();
    remark = json['remark']?.toString();
    empImg = json['emp_img']?.toString();
    titleName = json['title_name']?.toString();
    name = json['name']?.toString();
    titleNameEn = json['title_name_en']?.toString();
    nameEn = json['name_en']?.toString();
    citizenId = json['citizen_id']?.toString();
    taxId = json['tax_id']?.toString();
    socialInsuranceId = json['social_insurance_id']?.toString();
    nickName = json['nick_name']?.toString();
    gender = json['gender']?.toString();
    weight = json['weight']?.toString();
    height = json['height']?.toString();
    birthdate = json['birthdate']?.toString();
    bloodGroup = json['blood_group']?.toString();
    nationalityId = json['nationality_id']?.toString();
    religionId = json['religion_id']?.toString();
    militaryStatus = json['military_status']?.toString();
    marriedStatus = json['married_status']?.toString();
    tel = json['tel']?.toString();
    socialContact_1 = json['social_contact_1']?.toString();
    empCode = json['emp_code']?.toString();
    empTypeId = json['emp_type_id']?.toString();
    empGroupId = json['emp_group_id']?.toString();
    departmentId = json['department_id']?.toString();
    sectionId = json['section_id']?.toString();
    positionId = json['position_id']?.toString();
    groupDayOfWorkId = json['group_day_of_work_id']?.toString();
    shiftId = json['shift_id']?.toString();
    holidayLeave = json['holiday_leave']?.toString();
    fingerSign = json['finger_sign']?.toString();
    empWorkStatus = json['emp_work_status']?.toString();
    payType = json['pay_type']?.toString();
    payTerm = json['pay_term']?.toString();
    taxCalcId = json['tax_calc_id']?.toString();
    masterBankId = json['master_bank_id']?.toString();
    bankAccountNo = json['bank_account_no']?.toString();
    bankAccountName = json['bank_account_name']?.toString();
    socialInsuranceMethodLv = json['social_insurance_method_lv']?.toString();
    contractNo = json['contract_no']?.toString();
    hireDate = json['hire_date']?.toString();
    hireEnd = json['hire_end']?.toString();
    startDate = json['start_date']?.toString();
    dateOfAttendance = json['date_of_attendance']?.toString();
    wageValue = json['wage_value']?.toString();
    probationDays = json['probation_days']?.toString();
    address_1 = json['address_1']?.toString();
    provinceId_1 = json['province_id_1']?.toString();
    amphureId_1 = json['amphure_id_1']?.toString();
    tambolId_1 = json['tambol_id_1']?.toString();
    postalCode_1 = json['postal_code_1']?.toString();
    isSameAddress = json['is_same_address']?.toString();
    address_2 = json['address_2']?.toString();
    provinceId_2 = json['province_id_2']?.toString();
    amphureId_2 = json['amphure_id_2']?.toString();
    tambolId_2 = json['tambol_id_2']?.toString();
    postalCode_2 = json['postal_code_2']?.toString();
    personRelateName = json['person_relate_name']?.toString();
    personRelateTel = json['person_relate_tel']?.toString();
    personRelateDescription = json['person_relate_description']?.toString();
    languageSkill_1 = json['language_skill_1']?.toString();
    languagePoint_1 = json['language_point_1']?.toString();
    languageTalk_1 = json['language_talk_1']?.toString();
    languageRead_1 = json['language_read_1']?.toString();
    languageWrite_1 = json['language_write_1']?.toString();
    languageSkill_2 = json['language_skill_2']?.toString();
    languagePoint_2 = json['language_point_2']?.toString();
    languageTalk_2 = json['language_talk_2']?.toString();
    languageRead_2 = json['language_read_2']?.toString();
    languageWrite_2 = json['language_write_2']?.toString();
    motorcycleDrivingSkill = json['motorcycle_driving_skill']?.toString();
    motorcycleDrivingLicence = json['motorcycle_driving_licence']?.toString();
    motorcycleHave = json['motorcycle_have']?.toString();
    carDrivingSkill = json['car_driving_skill']?.toString();
    carDrivingLicence = json['car_driving_licence']?.toString();
    carHave = json['car_have']?.toString();
    passportId = json['passport_id']?.toString();
    passportDate = json['passport_date']?.toString();
    passportEndDate = json['passport_end_date']?.toString();
    visaId = json['visa_id']?.toString();
    visaDate = json['visa_date']?.toString();
    visaEndDate = json['visa_end_date']?.toString();
    isExpat = json['is_expat']?.toString();
    createdAt = json['created_at']?.toString();
    createdBy = json['created_by']?.toString();
    updatedAt = json['updated_at']?.toString();
    updatedBy = json['updated_by']?.toString();
    status = json['status']?.toString();
    helper = json['helper']?.toString();
    checkTerms = json['check_terms']?.toString();
    sysUserType = json['sys_user_type']?.toString();
    isPermitLogin = json['is_permit_login']?.toString();
    empLevel = json['emp_level']?.toString();
    empEducationId = json['emp_education_id']?.toString();
    taxCalcValue = json['tax_calc_value']?.toString();
    terminationReportDate = json['termination_report_date']?.toString();
    terminationDate = json['termination_date']?.toString();
    terminationApproveBy = json['termination_approve_by']?.toString();
    terminationAt = json['termination_at']?.toString();
    terminationRemark = json['termination_remark']?.toString();
    isTermination = json['is_termination']?.toString();
    retireDate = json['retire_date']?.toString();
    retireReportDate = json['retire_report_date']?.toString();
    retireBy = json['retire_by']?.toString();
    retireAt = json['retire_at']?.toString();
    retireRemark = json['retire_remark']?.toString();
    suspendAt = json['suspend_at']?.toString();
    suspendDate = json['suspend_date']?.toString();
    suspendReportDate = json['suspend_report_date']?.toString();
    suspendBy = json['suspend_by']?.toString();
    suspendRemark = json['suspend_remark']?.toString();
    quitDate = json['quit_date']?.toString();
    quitReportDate = json['quit_report_date']?.toString();
    quitBy = json['quit_by']?.toString();
    quitRemark = json['quit_remark']?.toString();
    quitAt = json['quit_at']?.toString();
    ipAddress = json['ip_address']?.toString();
    hospitalName = json['hospital_name']?.toString();
    docName_1 = json['doc_name_1']?.toString();
    docNumb_1 = json['doc_numb_1']?.toString();
    docDate_1 = json['doc_date_1']?.toString();
    docEndDate_1 = json['doc_end_date_1']?.toString();
    docAlert_1 = json['doc_alert_1']?.toString();
    docName_2 = json['doc_name_2']?.toString();
    docNumb_2 = json['doc_numb_2']?.toString();
    docDate_2 = json['doc_date_2']?.toString();
    docEndDate_2 = json['doc_end_date_2']?.toString();
    docAlert_2 = json['doc_alert_2']?.toString();
    docName_3 = json['doc_name_3']?.toString();
    docNumb_3 = json['doc_numb_3']?.toString();
    docDate_3 = json['doc_date_3']?.toString();
    docEndDate_3 = json['doc_end_date_3']?.toString();
    docAlert_3 = json['doc_alert_3']?.toString();
    docName_4 = json['doc_name_4']?.toString();
    docNumb_4 = json['doc_numb_4']?.toString();
    docDate_4 = json['doc_date_4']?.toString();
    docEndDate_4 = json['doc_end_date_4']?.toString();
    docAlert_4 = json['doc_alert_4']?.toString();
    requestDelete = json['request_delete']?.toString();
    tourStatus_01 = json['tour_status_01']?.toString();
    methodCreateType = json['method_create_type']?.toString();
    shortcutSetting = json['shortcut_setting']?.toString();
    joinDepartment = json['join_department']?.toString();
    joinSection = json['join_section']?.toString();
    joinPosition = json['join_position']?.toString();
    joinBank = json['join_bank']?.toString();
    joinGroupDayOfWork = json['join_group_day_of_work']?.toString();
    joinShift = json['join_shift']?.toString();
    joinNationality = json['join_nationality']?.toString();
    joinProvinceId_1 = json['join_province_id_1']?.toString();
    joinAmphureId_1 = json['join_amphure_id_1']?.toString();
    joinTambolId_1 = json['join_tambol_id_1']?.toString();
    joinProvinceId_2 = json['join_province_id_2']?.toString();
    joinAmphureId_2 = json['join_amphure_id_2']?.toString();
    joinTambolId_2 = json['join_tambol_id_2']?.toString();
    joinEducation = json['join_education']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['password'] = password;
    data['user_level'] = userLevel;
    data['user_type'] = userType;
    data['company_id'] = companyId;
    data['sys_customer_code'] = sysCustomerCode;
    data['profile_img'] = profileImg;
    data['is_active'] = isActive;
    data['is_delete'] = isDelete;
    data['remark'] = remark;
    data['emp_img'] = empImg;
    data['title_name'] = titleName;
    data['name'] = name;
    data['title_name_en'] = titleNameEn;
    data['name_en'] = nameEn;
    data['citizen_id'] = citizenId;
    data['tax_id'] = taxId;
    data['social_insurance_id'] = socialInsuranceId;
    data['nick_name'] = nickName;
    data['gender'] = gender;
    data['weight'] = weight;
    data['height'] = height;
    data['birthdate'] = birthdate;
    data['blood_group'] = bloodGroup;
    data['nationality_id'] = nationalityId;
    data['religion_id'] = religionId;
    data['military_status'] = militaryStatus;
    data['married_status'] = marriedStatus;
    data['tel'] = tel;
    data['social_contact_1'] = socialContact_1;
    data['emp_code'] = empCode;
    data['emp_type_id'] = empTypeId;
    data['emp_group_id'] = empGroupId;
    data['department_id'] = departmentId;
    data['section_id'] = sectionId;
    data['position_id'] = positionId;
    data['group_day_of_work_id'] = groupDayOfWorkId;
    data['shift_id'] = shiftId;
    data['holiday_leave'] = holidayLeave;
    data['finger_sign'] = fingerSign;
    data['emp_work_status'] = empWorkStatus;
    data['pay_type'] = payType;
    data['pay_term'] = payTerm;
    data['tax_calc_id'] = taxCalcId;
    data['master_bank_id'] = masterBankId;
    data['bank_account_no'] = bankAccountNo;
    data['bank_account_name'] = bankAccountName;
    data['social_insurance_method_lv'] = socialInsuranceMethodLv;
    data['contract_no'] = contractNo;
    data['hire_date'] = hireDate;
    data['hire_end'] = hireEnd;
    data['start_date'] = startDate;
    data['date_of_attendance'] = dateOfAttendance;
    data['wage_value'] = wageValue;
    data['probation_days'] = probationDays;
    data['address_1'] = address_1;
    data['province_id_1'] = provinceId_1;
    data['amphure_id_1'] = amphureId_1;
    data['tambol_id_1'] = tambolId_1;
    data['postal_code_1'] = postalCode_1;
    data['is_same_address'] = isSameAddress;
    data['address_2'] = address_2;
    data['province_id_2'] = provinceId_2;
    data['amphure_id_2'] = amphureId_2;
    data['tambol_id_2'] = tambolId_2;
    data['postal_code_2'] = postalCode_2;
    data['person_relate_name'] = personRelateName;
    data['person_relate_tel'] = personRelateTel;
    data['person_relate_description'] = personRelateDescription;
    data['language_skill_1'] = languageSkill_1;
    data['language_point_1'] = languagePoint_1;
    data['language_talk_1'] = languageTalk_1;
    data['language_read_1'] = languageRead_1;
    data['language_write_1'] = languageWrite_1;
    data['language_skill_2'] = languageSkill_2;
    data['language_point_2'] = languagePoint_2;
    data['language_talk_2'] = languageTalk_2;
    data['language_read_2'] = languageRead_2;
    data['language_write_2'] = languageWrite_2;
    data['motorcycle_driving_skill'] = motorcycleDrivingSkill;
    data['motorcycle_driving_licence'] = motorcycleDrivingLicence;
    data['motorcycle_have'] = motorcycleHave;
    data['car_driving_skill'] = carDrivingSkill;
    data['car_driving_licence'] = carDrivingLicence;
    data['car_have'] = carHave;
    data['passport_id'] = passportId;
    data['passport_date'] = passportDate;
    data['passport_end_date'] = passportEndDate;
    data['visa_id'] = visaId;
    data['visa_date'] = visaDate;
    data['visa_end_date'] = visaEndDate;
    data['is_expat'] = isExpat;
    data['created_at'] = createdAt;
    data['created_by'] = createdBy;
    data['updated_at'] = updatedAt;
    data['updated_by'] = updatedBy;
    data['status'] = status;
    data['helper'] = helper;
    data['check_terms'] = checkTerms;
    data['sys_user_type'] = sysUserType;
    data['is_permit_login'] = isPermitLogin;
    data['emp_level'] = empLevel;
    data['emp_education_id'] = empEducationId;
    data['tax_calc_value'] = taxCalcValue;
    data['termination_report_date'] = terminationReportDate;
    data['termination_date'] = terminationDate;
    data['termination_approve_by'] = terminationApproveBy;
    data['termination_at'] = terminationAt;
    data['termination_remark'] = terminationRemark;
    data['is_termination'] = isTermination;
    data['retire_date'] = retireDate;
    data['retire_report_date'] = retireReportDate;
    data['retire_by'] = retireBy;
    data['retire_at'] = retireAt;
    data['retire_remark'] = retireRemark;
    data['suspend_at'] = suspendAt;
    data['suspend_date'] = suspendDate;
    data['suspend_report_date'] = suspendReportDate;
    data['suspend_by'] = suspendBy;
    data['suspend_remark'] = suspendRemark;
    data['quit_date'] = quitDate;
    data['quit_report_date'] = quitReportDate;
    data['quit_by'] = quitBy;
    data['quit_remark'] = quitRemark;
    data['quit_at'] = quitAt;
    data['ip_address'] = ipAddress;
    data['hospital_name'] = hospitalName;
    data['doc_name_1'] = docName_1;
    data['doc_numb_1'] = docNumb_1;
    data['doc_date_1'] = docDate_1;
    data['doc_end_date_1'] = docEndDate_1;
    data['doc_alert_1'] = docAlert_1;
    data['doc_name_2'] = docName_2;
    data['doc_numb_2'] = docNumb_2;
    data['doc_date_2'] = docDate_2;
    data['doc_end_date_2'] = docEndDate_2;
    data['doc_alert_2'] = docAlert_2;
    data['doc_name_3'] = docName_3;
    data['doc_numb_3'] = docNumb_3;
    data['doc_date_3'] = docDate_3;
    data['doc_end_date_3'] = docEndDate_3;
    data['doc_alert_3'] = docAlert_3;
    data['doc_name_4'] = docName_4;
    data['doc_numb_4'] = docNumb_4;
    data['doc_date_4'] = docDate_4;
    data['doc_end_date_4'] = docEndDate_4;
    data['doc_alert_4'] = docAlert_4;
    data['request_delete'] = requestDelete;
    data['tour_status_01'] = tourStatus_01;
    data['method_create_type'] = methodCreateType;
    data['shortcut_setting'] = shortcutSetting;
    data['join_department'] = joinDepartment;
    data['join_section'] = joinSection;
    data['join_position'] = joinPosition;
    data['join_bank'] = joinBank;
    data['join_group_day_of_work'] = joinGroupDayOfWork;
    data['join_shift'] = joinShift;
    data['join_nationality'] = joinNationality;
    data['join_province_id_1'] = joinProvinceId_1;
    data['join_amphure_id_1'] = joinAmphureId_1;
    data['join_tambol_id_1'] = joinTambolId_1;
    data['join_province_id_2'] = joinProvinceId_2;
    data['join_amphure_id_2'] = joinAmphureId_2;
    data['join_tambol_id_2'] = joinTambolId_2;
    data['join_education'] = joinEducation;
    return data;
  }
}

class UserTimeStampModelData {

  String? timesheetId;
  String? date;
  String? personId;
  String? companyId;
  String? time;
  String? timesheetCreatedAt;
  String? timesheetCreatedBy;
  String? timesheetUpdatedAt;
  String? timesheetUpdatedBy;
  String? latitude;
  String? longitude;
  String? in_1At;
  String? out_1At;
  UserTimeStampModelDataEmpInfo? empInfo;

  UserTimeStampModelData({
    this.timesheetId,
    this.date,
    this.personId,
    this.companyId,
    this.time,
    this.timesheetCreatedAt,
    this.timesheetCreatedBy,
    this.timesheetUpdatedAt,
    this.timesheetUpdatedBy,
    this.latitude,
    this.longitude,
    this.in_1At,
    this.out_1At,
    this.empInfo,
  });
  UserTimeStampModelData.fromJson(Map<String, dynamic> json) {
    timesheetId = json['timesheet_id']?.toString();
    date = json['date']?.toString();
    personId = json['person_id']?.toString();
    companyId = json['company_id']?.toString();
    time = json['time']?.toString();
    timesheetCreatedAt = json['timesheet_created_at']?.toString();
    timesheetCreatedBy = json['timesheet_created_by']?.toString();
    timesheetUpdatedAt = json['timesheet_updated_at']?.toString();
    timesheetUpdatedBy = json['timesheet_updated_by']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    in_1At = json['in_1_at']?.toString();
    out_1At = json['out_1_at']?.toString();
    empInfo = (json['emp_info'] != null) ? UserTimeStampModelDataEmpInfo.fromJson(json['emp_info']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['timesheet_id'] = timesheetId;
    data['date'] = date;
    data['person_id'] = personId;
    data['company_id'] = companyId;
    data['time'] = time;
    data['timesheet_created_at'] = timesheetCreatedAt;
    data['timesheet_created_by'] = timesheetCreatedBy;
    data['timesheet_updated_at'] = timesheetUpdatedAt;
    data['timesheet_updated_by'] = timesheetUpdatedBy;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['in_1_at'] = in_1At;
    data['out_1_at'] = out_1At;
    if (empInfo != null) {
      data['emp_info'] = empInfo!.toJson();
    }
    return data;
  }
}

class UserTimeStampModel {


  

  UserTimeStampModelData? data;
  String? message;
  String? messageEx;
  bool? success;
  String? errors;

  UserTimeStampModel({
    this.data,
    this.message,
    this.messageEx,
    this.success,
    this.errors,
  });
  UserTimeStampModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? UserTimeStampModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
    messageEx = json['message_ex']?.toString();
    success = json['success'];
    errors = json['errors']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    data['message_ex'] = messageEx;
    data['success'] = success;
    data['errors'] = errors;
    return data;
  }
}
